This workflow can be used to automate tasks for the DV-020-Develop-object-oriented-CSharp project on GitHub. You can customize it based on your specific needs.

name: DV-020 CSharp Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'  # Update with desired version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release

      - name: Run tests (optional)
        run: dotnet test --no-build --configuration Release

      - name: Upload test results (optional)
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: **/test/**/results.xml
